# TCL File Generated by Component Editor 13.0sp1
# Tue May 02 20:41:33 EEST 2017
# DO NOT MODIFY


# 
# direct_vga "direct_vga" v1.0
#  2017.05.02.20:41:33
# 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module direct_vga
# 
set_module_property DESCRIPTION ""
set_module_property NAME direct_vga
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "my own components"
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME direct_vga
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL direct_vga
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file direct_vga.vhd VHDL PATH direct_vga.vhd TOP_LEVEL_FILE

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL direct_vga
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file direct_vga.vhd VHDL PATH direct_vga.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock nios_clock
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink reset reset Input 1


# 
# connection point s1
# 
add_interface s1 avalon end
set_interface_property s1 addressUnits WORDS
set_interface_property s1 associatedClock nios_clock
set_interface_property s1 associatedReset reset_sink
set_interface_property s1 bitsPerSymbol 8
set_interface_property s1 burstOnBurstBoundariesOnly false
set_interface_property s1 burstcountUnits WORDS
set_interface_property s1 explicitAddressSpan 0
set_interface_property s1 holdTime 0
set_interface_property s1 linewrapBursts false
set_interface_property s1 maximumPendingReadTransactions 0
set_interface_property s1 readLatency 0
set_interface_property s1 readWaitTime 1
set_interface_property s1 setupTime 0
set_interface_property s1 timingUnits Cycles
set_interface_property s1 writeWaitTime 0
set_interface_property s1 ENABLED true
set_interface_property s1 EXPORT_OF ""
set_interface_property s1 PORT_NAME_MAP ""
set_interface_property s1 SVD_ADDRESS_GROUP ""

add_interface_port s1 writedata writedata Input 32
add_interface_port s1 write_req write Input 1
add_interface_port s1 address address Input 1
set_interface_assignment s1 embeddedsw.configuration.isFlash 0
set_interface_assignment s1 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment s1 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment s1 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point vga_clock
# 
add_interface vga_clock clock end
set_interface_property vga_clock clockRate 0
set_interface_property vga_clock ENABLED true
set_interface_property vga_clock EXPORT_OF ""
set_interface_property vga_clock PORT_NAME_MAP ""
set_interface_property vga_clock SVD_ADDRESS_GROUP ""

add_interface_port vga_clock vga_clock clk Input 1


# 
# connection point nios_clock
# 
add_interface nios_clock clock end
set_interface_property nios_clock clockRate 0
set_interface_property nios_clock ENABLED true
set_interface_property nios_clock EXPORT_OF ""
set_interface_property nios_clock PORT_NAME_MAP ""
set_interface_property nios_clock SVD_ADDRESS_GROUP ""

add_interface_port nios_clock nios_clock clk Input 1


# 
# connection point out_vga
# 
add_interface out_vga conduit end
set_interface_property out_vga associatedClock ""
set_interface_property out_vga associatedReset ""
set_interface_property out_vga ENABLED true
set_interface_property out_vga EXPORT_OF ""
set_interface_property out_vga PORT_NAME_MAP ""
set_interface_property out_vga SVD_ADDRESS_GROUP ""

add_interface_port out_vga video_r export Output 8
add_interface_port out_vga video_g export Output 8
add_interface_port out_vga video_b export Output 8
add_interface_port out_vga video_hsync export Output 1
add_interface_port out_vga video_vsync export Output 1


# 
# connection point interrupt_sender
# 
add_interface interrupt_sender interrupt end
set_interface_property interrupt_sender associatedAddressablePoint s1
set_interface_property interrupt_sender associatedClock nios_clock
set_interface_property interrupt_sender associatedReset reset_sink
set_interface_property interrupt_sender ENABLED true
set_interface_property interrupt_sender EXPORT_OF ""
set_interface_property interrupt_sender PORT_NAME_MAP ""
set_interface_property interrupt_sender SVD_ADDRESS_GROUP ""

add_interface_port interrupt_sender frame_irq irq Output 1

