# TCL File Generated by Component Editor 13.0sp1
# Mon Apr 24 14:04:55 EEST 2017
# DO NOT MODIFY


# 
# simple_vga "simple_vga" v1.0
#  2017.04.24.14:04:55
# 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module simple_vga
# 
set_module_property DESCRIPTION ""
set_module_property NAME simple_vga
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "my own components"
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME simple_vga
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL simple_vga
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file simple_vga.vhd VHDL PATH simple_vga.vhd TOP_LEVEL_FILE

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL simple_vga
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file simple_vga.vhd VHDL PATH simple_vga.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink clock clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink reset reset Input 1


# 
# connection point in_leds
# 
add_interface in_leds conduit end
set_interface_property in_leds associatedClock ""
set_interface_property in_leds associatedReset ""
set_interface_property in_leds ENABLED true
set_interface_property in_leds EXPORT_OF ""
set_interface_property in_leds PORT_NAME_MAP ""
set_interface_property in_leds SVD_ADDRESS_GROUP ""

add_interface_port in_leds in_leds export Input 8


# 
# connection point out_vga
# 
add_interface out_vga conduit end
set_interface_property out_vga associatedClock ""
set_interface_property out_vga associatedReset ""
set_interface_property out_vga ENABLED true
set_interface_property out_vga EXPORT_OF ""
set_interface_property out_vga PORT_NAME_MAP ""
set_interface_property out_vga SVD_ADDRESS_GROUP ""

add_interface_port out_vga video_r export Output 8
add_interface_port out_vga video_g export Output 8
add_interface_port out_vga video_b export Output 8
add_interface_port out_vga video_hsync export Output 1
add_interface_port out_vga video_vsync export Output 1

