// proc_nios_0.v

// Generated using ACDS version 13.0sp1 232 at 2017.04.07.22:24:25

`timescale 1 ps / 1 ps
module proc_nios_0 (
		input  wire  clk_clk,       //   clk.clk
		input  wire  reset_reset_n  // reset.reset_n
	);

	proc_nios_0_nios_0 nios_0 (
	);

endmodule
