// proc.v

// Generated using ACDS version 13.0sp1 232 at 2017.04.07.22:24:25

`timescale 1 ps / 1 ps
module proc (
		input  wire  clk_clk,         //     clk.clk
		input  wire  reset_reset_n,   //   reset.reset_n
		input  wire  clk_0_clk,       //   clk_0.clk
		input  wire  reset_0_reset_n, // reset_0.reset_n
		input  wire  clk_1_clk,       //   clk_1.clk
		input  wire  reset_1_reset_n  // reset_1.reset_n
	);

	proc_nios_0 nios_0 (
		.clk_clk       (clk_0_clk),       //   clk.clk
		.reset_reset_n (reset_0_reset_n)  // reset.reset_n
	);

endmodule
