// nios.v

// Generated using ACDS version 13.0sp1 232 at 2017.04.07.22:21:34

`timescale 1 ps / 1 ps
module nios (
		input  wire  clk_clk,         //     clk.clk
		input  wire  reset_reset_n,   //   reset.reset_n
		input  wire  clk_0_clk,       //   clk_0.clk
		input  wire  reset_0_reset_n  // reset_0.reset_n
	);

	nios_nios_0 nios_0 (
		.clk_clk       (clk_0_clk),       //   clk.clk
		.reset_reset_n (reset_0_reset_n)  // reset.reset_n
	);

endmodule
