# TCL File Generated by Component Editor 13.0sp1
# Sun Apr 23 23:40:54 EEST 2017
# DO NOT MODIFY


# 
# vga_controller "VGA Controller" v1.3
# Darius Kellermann, Max Stolze 2017.04.23.23:40:54
# This IP includes a VGA Core with DMA capabilities to access a framebuffer located in RAM or ROM.
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module vga_controller
# 
set_module_property DESCRIPTION "This IP includes a VGA Core with DMA capabilities to access a framebuffer located in RAM or ROM."
set_module_property NAME vga_controller
set_module_property VERSION 1.3
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Peripherals/Display
set_module_property AUTHOR "Darius Kellermann, Max Stolze"
set_module_property ICON_PATH logo.jpg
set_module_property DISPLAY_NAME "VGA Controller"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset quartus_synth QUARTUS_SYNTH "" "Quartus Synthesis"
set_fileset_property quartus_synth TOP_LEVEL vga_controller
set_fileset_property quartus_synth ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file vga_controller.vhd VHDL PATH vga_controller.vhd TOP_LEVEL_FILE
add_fileset_file vga_controller_dma_vga_logic.vhd VHDL PATH vga_controller_dma_vga_logic.vhd
add_fileset_file vga_controller_registers.vhd VHDL PATH vga_controller_registers.vhd
add_fileset_file vga_controller_vga_signals.vhd VHDL PATH vga_controller_vga_signals.vhd
add_fileset_file vga_controller_fifo.vhd VHDL PATH vga_controller_fifo.vhd

add_fileset sim_vhdl SIM_VHDL "" "VHDL Simulation"
set_fileset_property sim_vhdl ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file vga_controller.vhd VHDL PATH vga_controller.vhd
add_fileset_file vga_controller_dma_vga_logic.vhd VHDL PATH vga_controller_dma_vga_logic.vhd
add_fileset_file vga_controller_registers.vhd VHDL PATH vga_controller_registers.vhd
add_fileset_file vga_controller_vga_signals.vhd VHDL PATH vga_controller_vga_signals.vhd
add_fileset_file vga_controller_fifo.vhd VHDL PATH vga_controller_fifo.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clk_snk_reset
# 
add_interface clk_snk_reset reset end
set_interface_property clk_snk_reset associatedClock clk_snk
set_interface_property clk_snk_reset synchronousEdges DEASSERT
set_interface_property clk_snk_reset ENABLED true
set_interface_property clk_snk_reset EXPORT_OF ""
set_interface_property clk_snk_reset PORT_NAME_MAP ""
set_interface_property clk_snk_reset SVD_ADDRESS_GROUP ""

add_interface_port clk_snk_reset csi_clk_snk_reset reset Input 1


# 
# connection point clk_snk
# 
add_interface clk_snk clock end
set_interface_property clk_snk clockRate 0
set_interface_property clk_snk ENABLED true
set_interface_property clk_snk EXPORT_OF ""
set_interface_property clk_snk PORT_NAME_MAP ""
set_interface_property clk_snk SVD_ADDRESS_GROUP ""

add_interface_port clk_snk csi_clk_snk_clk clk Input 1


# 
# connection point controll
# 
add_interface controll avalon end
set_interface_property controll addressUnits WORDS
set_interface_property controll associatedClock clk_snk
set_interface_property controll associatedReset clk_snk_reset
set_interface_property controll bitsPerSymbol 8
set_interface_property controll burstOnBurstBoundariesOnly false
set_interface_property controll burstcountUnits WORDS
set_interface_property controll explicitAddressSpan 0
set_interface_property controll holdTime 0
set_interface_property controll linewrapBursts false
set_interface_property controll maximumPendingReadTransactions 0
set_interface_property controll readLatency 0
set_interface_property controll readWaitTime 1
set_interface_property controll setupTime 0
set_interface_property controll timingUnits Cycles
set_interface_property controll writeWaitTime 0
set_interface_property controll ENABLED true
set_interface_property controll EXPORT_OF ""
set_interface_property controll PORT_NAME_MAP ""
set_interface_property controll SVD_ADDRESS_GROUP ""

add_interface_port controll avs_controll_write write Input 1
add_interface_port controll avs_controll_address address Input 1
add_interface_port controll avs_controll_writedata writedata Input 32
set_interface_assignment controll embeddedsw.configuration.isFlash 0
set_interface_assignment controll embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment controll embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment controll embeddedsw.configuration.isPrintableDevice 0


# 
# connection point dma
# 
add_interface dma avalon start
set_interface_property dma addressUnits SYMBOLS
set_interface_property dma associatedClock clk_snk
set_interface_property dma associatedReset clk_snk_reset
set_interface_property dma bitsPerSymbol 8
set_interface_property dma burstOnBurstBoundariesOnly false
set_interface_property dma burstcountUnits WORDS
set_interface_property dma doStreamReads false
set_interface_property dma doStreamWrites false
set_interface_property dma holdTime 0
set_interface_property dma linewrapBursts false
set_interface_property dma maximumPendingReadTransactions 0
set_interface_property dma readLatency 0
set_interface_property dma readWaitTime 1
set_interface_property dma setupTime 0
set_interface_property dma timingUnits Cycles
set_interface_property dma writeWaitTime 0
set_interface_property dma ENABLED true
set_interface_property dma EXPORT_OF ""
set_interface_property dma PORT_NAME_MAP ""
set_interface_property dma SVD_ADDRESS_GROUP ""

add_interface_port dma avm_dma_waitrequest waitrequest Input 1
add_interface_port dma avm_dma_readdata readdata Input 64
add_interface_port dma avm_dma_readdatavalid readdatavalid Input 1
add_interface_port dma avm_dma_address address Output 32
add_interface_port dma avm_dma_read read Output 1
add_interface_port dma avm_dma_byteenable byteenable Output 8
add_interface_port dma avm_dma_burstcount burstcount Output 6


# 
# connection point vga_hs
# 
add_interface vga_hs conduit end
set_interface_property vga_hs associatedClock ""
set_interface_property vga_hs associatedReset ""
set_interface_property vga_hs ENABLED true
set_interface_property vga_hs EXPORT_OF ""
set_interface_property vga_hs PORT_NAME_MAP ""
set_interface_property vga_hs SVD_ADDRESS_GROUP ""

add_interface_port vga_hs coe_vga_hs_export export Output 1


# 
# connection point vga_vs
# 
add_interface vga_vs conduit end
set_interface_property vga_vs associatedClock ""
set_interface_property vga_vs associatedReset ""
set_interface_property vga_vs ENABLED true
set_interface_property vga_vs EXPORT_OF ""
set_interface_property vga_vs PORT_NAME_MAP ""
set_interface_property vga_vs SVD_ADDRESS_GROUP ""

add_interface_port vga_vs coe_vga_vs_export export Output 1


# 
# connection point vga_r
# 
add_interface vga_r conduit end
set_interface_property vga_r associatedClock ""
set_interface_property vga_r associatedReset ""
set_interface_property vga_r ENABLED true
set_interface_property vga_r EXPORT_OF ""
set_interface_property vga_r PORT_NAME_MAP ""
set_interface_property vga_r SVD_ADDRESS_GROUP ""

add_interface_port vga_r coe_vga_r_export export Output 4


# 
# connection point vga_g
# 
add_interface vga_g conduit end
set_interface_property vga_g associatedClock ""
set_interface_property vga_g associatedReset ""
set_interface_property vga_g ENABLED true
set_interface_property vga_g EXPORT_OF ""
set_interface_property vga_g PORT_NAME_MAP ""
set_interface_property vga_g SVD_ADDRESS_GROUP ""

add_interface_port vga_g coe_vga_g_export export Output 4


# 
# connection point vga_b
# 
add_interface vga_b conduit end
set_interface_property vga_b associatedClock ""
set_interface_property vga_b associatedReset ""
set_interface_property vga_b ENABLED true
set_interface_property vga_b EXPORT_OF ""
set_interface_property vga_b PORT_NAME_MAP ""
set_interface_property vga_b SVD_ADDRESS_GROUP ""

add_interface_port vga_b coe_vga_b_export export Output 4

